import DeveloperImage from "../../assets/Team/Developer.jpg";

const TeamData = [
  {
    img: DeveloperImage,
    name: "John Doi",
    position: " Tech Team",
    GitHub: "https://github.com/AbhiPatel10",
    LinkedIn: "https://www.linkedin.com/in/abhipatel001/",
    Twitter: "https://twitter.com/AbhiPatel0001",
  },
  {
    img: DeveloperImage,
    name: "John Doi",
    position: " Tech Team",
    GitHub: "https://github.com/AbhiPatel10",
    LinkedIn: "https://www.linkedin.com/in/abhipatel001/",
    Twitter: "https://twitter.com/AbhiPatel0001",
  },
  {
    img: DeveloperImage,
    name: "John Doi",
    position: " Tech Team",
    GitHub: "https://github.com/AbhiPatel10",
    LinkedIn: "https://www.linkedin.com/in/abhipatel001/",
    Twitter: "https://twitter.com/AbhiPatel0001",
  },
  {
    img: DeveloperImage,
    name: "John Doi",
    position: " Tech Team",
    GitHub: "https://github.com/AbhiPatel10",
    LinkedIn: "https://www.linkedin.com/in/abhipatel001/",
    Twitter: "https://twitter.com/AbhiPatel0001",
  },
  {
    img: DeveloperImage,
    name: "John Doi",
    position: " Tech Team",
    GitHub: "https://github.com/AbhiPatel10",
    LinkedIn: "https://www.linkedin.com/in/abhipatel001/",
    Twitter: "https://twitter.com/AbhiPatel0001",
  },
  {
    img: DeveloperImage,
    name: "John Doi",
    position: " Tech Team",
    GitHub: "https://github.com/AbhiPatel10",
    LinkedIn: "https://www.linkedin.com/in/abhipatel001/",
    Twitter: "https://twitter.com/AbhiPatel0001",
  },
  {
    img: DeveloperImage,
    name: "John Doi",
    position: " Tech Team",
    GitHub: "https://github.com/AbhiPatel10",
    LinkedIn: "https://www.linkedin.com/in/abhipatel001/",
    Twitter: "https://twitter.com/AbhiPatel0001",
  },
  {
    img: DeveloperImage,
    name: "John Doi",
    position: " Tech Team",
    GitHub: "https://github.com/AbhiPatel10",
    LinkedIn: "https://www.linkedin.com/in/abhipatel001/",
    Twitter: "https://twitter.com/AbhiPatel0001",
  },
  {
    img: DeveloperImage,
    name: "John Doi",
    position: " Tech Team",
    GitHub: "https://github.com/AbhiPatel10",
    LinkedIn: "https://www.linkedin.com/in/abhipatel001/",
    Twitter: "https://twitter.com/AbhiPatel0001",
  },
  {
    img: DeveloperImage,
    name: "John Doi",
    position: " Tech Team",
    GitHub: "https://github.com/AbhiPatel10",
    LinkedIn: "https://www.linkedin.com/in/abhipatel001/",
    Twitter: "https://twitter.com/AbhiPatel0001",
  },
];

export default TeamData;
