const TeamData = [
  {
    img: "https://github.com/Susmita-Dey.png?size=200",
    name: "Susmita Dey",
    position: "Co-Founder",
    GitHub: "https://github.com/Susmita-Dey",
    LinkedIn: "https://www.linkedin.com/in/susmita-dey-15a15a210/",
    Twitter: "https://twitter.com/its_SusmitaDey",
  },
  {
    img: "",
    name: "Abhirup Raha",
    position: "Co-Founder",
    GitHub: "",
    LinkedIn: "https://www.linkedin.com/in/abhirup-raha-502b08230/",
    Twitter: "",
  },
  {
    img: "https://github.com/himanshu1221.png?size=200",
    name: "Himanshu Chhatwal",
    position: "Dev Team",
    GitHub: "https://github.com/himanshu1221",
    LinkedIn: "https://www.linkedin.com/in/himanshuchhatwal/",
    Twitter: "https://twitter.com/himanshuchhatw2",
  },
  {
    img: "https://github.com/AbhiPatel10.png?size=200",
    name: "Abhi Patel",
    position: "Dev Team",
    GitHub: "https://github.com/AbhiPatel10",
    LinkedIn: "https://www.linkedin.com/in/abhipatel001/",
    Twitter: "https://twitter.com/AbhiPatel0001",
  },
  {
    img: "https://github.com/prnvtripathi.png?size=200",
    name: "Pranav Tripathi",
    position: "Dev Team",
    GitHub: "https://github.com/prnvtripathi",
    LinkedIn: "https://www.linkedin.com/in/tripathipranav14/",
    Twitter: "https://twitter.com/prnvtwts",
  },
  {
    img: "https://github.com/Vijaykv5.png?size=200",
    name: "Vijay Kumar",
    position: "UI/UX Team",
    GitHub: "https://github.com/Vijaykv5",
    LinkedIn: "https://www.linkedin.com/in/vijay-kv-159511222",
    Twitter: "",
  },
  {
    img: "https://github.com/kelvinparmar.png?size=200",
    name: "Kelvin Parmar",
    position: "Content Writing Team",
    GitHub: "https://github.com/kelvinparmar",
    LinkedIn: "https://www.linkedin.com/in/kelvinparmar",
    Twitter: "https://twitter.com/Kelvinparmar12",
  },
  {
    img: "https://github.com/RISHABH9450.png?size=200",
    name: "Rishabh Singh",
    position: "Content Writing Team",
    GitHub: "https://github.com/RISHABH9450",
    LinkedIn: "https://www.linkedin.com/in/rishabh-singh-9882b2184",
    Twitter: "https://twitter.com/Rizer529",
  },
  {
    img: "https://github.com/Malavi1.png?size=200",
    name: "Malavi Pande",
    position: "Content Writing Team",
    GitHub: "https://github.com/Malavi1",
    LinkedIn: "https://www.linkedin.com/in/malavipande/",
    Twitter: "https://twitter.com/molavi_418",
  },
  {
    img: "https://github.com/GaryHilares.png?size=200",
    name: "Gary Hilares",
    position: "Event Management Team",
    GitHub: "ttps://github.com/GaryHilares",
    LinkedIn: "https://www.linkedin.com/in/gary-hilares/",
    Twitter: "https://twitter.com/GaryHilares",
  },
  {
    img: "https://github.com/shaileshthakur1.png?size=200",
    name: "Shailesh Thakur",
    position: "Event Management Team",
    GitHub: "https://github.com/shaileshthakur1",
    LinkedIn:
      "https://www.linkedin.com/mwlite/in/shailesh-kumar-thakur-991316205",
    Twitter: "https://twitter.com/shylesstwts",
  },
  {
    img: "https://github.com/automatlog.png?size=200",
    name: "Aman Yadav",
    position: "Event Management Team",
    GitHub: "https://github.com/automatlog",
    LinkedIn: "https://www.linkedin.com/in/amandkyadav",
    Twitter: "https://twitter.com/automatlog",
  },

  {
    img: "https://github.com/prakhartiwari0.png?size=200",
    name: "Prakhar Tiwari",
    position: "Event Management Team",
    GitHub: "https://github.com/prakhartiwari0",
    LinkedIn: "https://www.linkedin.com/in/prakhartiwari0/",
    Twitter: "https://twitter.com/prakhartiwari0",
  },
];

export default TeamData;
